version: '3.6'
services:
  georgecolgrove:
    build: .
    volumes:
      - ./Server/logs/:/logs
    ports:
      - '${PORT}:80'
    environment:
      - NGINX_HOST=127.0.0.1
      - NGINX_PORT=${PORT}
