name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Beta Site
      run: |
        docker login --username captainglacier
        docker build . --file Dockerfile --tag captainglacier/angular-georgecolgrove:beta
        docker push captainglacier/angular-georgecolgrove:beta
