name: Build Prod Site

on: 
  push:
    branches: 
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Prod Site
      run: |
        docker login --username captainglacier --password ${{ secrets.DockerHubToken }}
        docker build . --file Dockerfile --tag captainglacier/angular-georgecolgrove:latest
        docker push captainglacier/angular-georgecolgrove:latest
