name: Build Beta Site

on: 
  push:
    branches: 
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Beta Site
      run: |
        docker login --username captainglacier --password ${{ secrets.DockerHubToken }}
        docker build . --file Dockerfile --tag captainglacier/angular-georgecolgrove:master
        docker push captainglacier/angular-georgecolgrove:master
